name: Workflow Dispatch

on:
  workflow_dispatch:
    inputs:
      comment:
        default: ""
      user:
        default: ""

jobs:
  test:
    name: Test
    steps:
      - name: Test
        run: echo $USER: $COMMENT
        env:
            USER: ${{ github.event.inputs.user }}
            COMMENT: ${{ github.event.inputs.comment }}

